### ISSUE TITLE
sort does not have --parallel option

### ISSUE THREAD

**Issue by bernt-matthias** [miinslin/ProteoStorm#1]
On our system sort does not have the `--parallel` option which makes ProteoStorm crash.

**Comment by bgruening** [comment]
We could add coreutils to a conda package to circumvent this.

**Comment by bgruening** [comment]
@bernt-matthias I was ask to assist in developing a Galaxy integration for this tool, but as far as I know you, you have done this already right? :)

**Comment by miinslin** [comment]
Apologies for the late reply! As I am the only person working on developing this tool, things are moving slower than usual. I have been working on an updated version of ProteoStorm, where we no longer use Unix sort (and thus no --parallel option necessary), and will be updating the repository within the next few days. The main difference will be on the approach we take when creating database partitions.

**Comment by bernt-matthias** [comment]
@miinslin wonderful. thanks a lot.

@bgruening no I did not start yet. I was just evaluating the tool from the command line. If it works well I could imagine to do the integration. we could share the work. you do the conda package and I do the galaxy tool :)

**Comment by bgruening** [comment]
Deal, I will just wait for @miinslin to publish the new version.

**Comment by bgruening** [comment]
btw. @miinslin it is completely ok to use unix-sort, it better to use it than to implement this by yourself. Such errors will go away with proper packaging, e.g. as conda or debian packages.

**Comment by bernt-matthias** [comment]
solved?

**Comment by miinslin** [comment]
Dear All, the database partitioning step no longer uses Unix sort, so I have closed the issue. Our manuscript is also now published on _Cell Systems_ as a tool article, and we have a detailed description of the software and algorithms in the STAR methods section. You can access the manuscript online [[Beyter and Lin et al., 2018](https://www.cell.com/cell-systems/fulltext/S2405-4712(18)30356-9).
